# Generated by Django 3.1.2 on 2020-10-29 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_entry_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.user')),
            ],
        ),
    ]
