# Generated by Django 3.1.2 on 2020-10-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumini',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.user')),
                ('college', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.college')),
            ],
        ),
    ]
