# Generated by Django 3.1.2 on 2020-10-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alumini_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumini',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.locations'),
        ),
    ]
