# Generated by Django 3.1.2 on 2020-10-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumini',
            name='salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.salary'),
        ),
    ]
